Testing the  ``say_my_name``  function from  ``3-say_my_name``  module 
============================================================================


Importing the  ``say_my_name``  function:
    >>> say_my_name = __import__("3-say_my_name").say_my_name


____________________________________________________________________________
[x] -> section 01 - Two valid arguments of type string
    >>> say_my_name("Fab", "The Great")
    My name is Fab The Great


____________________________________________________________________________
[x] -> section 02 - First argument of type string no second argument provided
    >>> say_my_name("Greatness")
    My name is Greatness 


____________________________________________________________________________
[x] -> section 03 - second argument is not a string
    >>> say_my_name("Fab", 7)
    Traceback (most recent call last):
        ...
    TypeError: last_name must be a string


____________________________________________________________________________
[x] -> section 04 - First arguments id not a string
    >>> say_my_name(7, "Fab")
    Traceback (most recent call last):
        ...
    TypeError: first_name must be a string


____________________________________________________________________________
[x] -> section 05 - both arguments are not strings
    >>> say_my_name(7, 10)
    Traceback (most recent call last):
        ...
    TypeError: first_name must be a string


____________________________________________________________________________
[x] -> section 06 - Both arguments are None
    >>> say_my_name(None, None)
    Traceback (most recent call last):
        ...
    TypeError: first_name must be a string


____________________________________________________________________________
[x] -> section 07 - No arguments provided
    >>> say_my_name()
    Traceback (most recent call last):
        ...
    TypeError: say_my_name() missing 1 required positional argument: 'first_name'

____________________________________________________________________________
[x] -> section 08 - too many arguments
    >>> say_my_name("Fab", "The", "Great")
    Traceback (most recent call last):
        ...
    TypeError: say_my_name() takes from 1 to 2 positional arguments but 3 were given
